version: '3.8'

services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "6001:6001"
    env_file:
      - .env  
    environment:
      - PORT=6001
      - JWT_SECRET=klea_ecommerce_super_secret_jwt_key_2024_microservices_auth
    networks:
      - ecommerce_network

  customer_service:
    build: ./customer_service
    container_name: customer_service
    ports:
      - "6002:6002"
    env_file:
      - .env  
    environment:
      - PORT=6002
    networks:
      - ecommerce_network

  inventory_service:
    build: ./inventory_service
    container_name: inventory_service
    ports:
      - "6003:6003"
    env_file:
      - .env  
    environment:
      - PORT=6003
    networks:
      - ecommerce_network

  payment_service:
    build: ./payment_service
    container_name: payment_service
    ports:
      - "6004:6004"
    env_file:
      - .env                  
    environment:
      - PORT=6004
    networks:
      - ecommerce_network

  order_service:
    build: ./order_service
    container_name: order_service
    ports:
      - "6005:6005"
    env_file:
      - .env  
    environment:
      - PORT=6005
    networks:
      - ecommerce_network

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "9080:9080"
    environment:
      - AUTH_SERVICE_URL=http://auth_service:6001
      - CUSTOMER_SERVICE_URL=http://customer_service:6002
      - INVENTORY_SERVICE_URL=http://inventory_service:6003
      - PAYMENT_SERVICE_URL=http://payment_service:6004
      - ORDER_SERVICE_URL=http://order_service:6005
      - PORT=9080
    depends_on:
      - auth_service
      - customer_service
      - inventory_service
      - payment_service
      - order_service
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge 